<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-04-13 16:22
=======
# Generated by Django 3.1.7 on 2021-04-13 16:19
>>>>>>> 54e1f4756d5ce8586bdf54d95f08f5819d5ea2f2

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feeding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
<<<<<<< HEAD
                ('meal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
=======
                ('meeal', models.CharField(choices=[('B', 'Breakfast'), ('L', 'Lunch'), ('D', 'Dinner')], default='B', max_length=1)),
>>>>>>> 54e1f4756d5ce8586bdf54d95f08f5819d5ea2f2
                ('cat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.cat')),
            ],
        ),
    ]
