# Generated by Django 3.1.7 on 2021-04-13 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_feeding'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feeding',
            old_name='meeal',
            new_name='meal',
        ),
    ]
