<<<<<<< HEAD
# Generated by Django 3.1.4 on 2021-04-15 16:20
=======
# Generated by Django 3.1.7 on 2021-04-15 16:20
>>>>>>> 816a649b97012fccce3c9fdd29c71137f0ac965f

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main_app', '0005_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.user'),
            preserve_default=False,
        ),
    ]
